### ISSUE TITLE
error while compiling version 0.4 for linux

### ISSUE THREAD

**Issue by UnicodeMan** [arqma/arqma-gui#42]
Compiling stops with this error:
Project ERROR: Unknown module(s) in QT: svg

This is because in README someone forgot to add package "libqt5svg5-dev
" as dependancy. If it is not already in the system by chance, compilation fails.
Installation of this dependancy leads to a successful compiling.

**Comment by ArqTras** [comment]
Thanks for the info -> checking right now

**Comment by ArqTras** [comment]
> 
> 
> Compiling stops with this error:
> Project ERROR: Unknown module(s) in QT: svg
> 
> This is because in README someone forgot to add package "libqt5svg5-dev
> " as dependancy. If it is not already in the system by chance, compilation fails.
> Installation of this dependancy leads to a successful compiling.

I did compile without that lib successfully Ubuntu 18.04 desktop
![gui](https://user-images.githubusercontent.com/33489188/59881015-d34ad480-93ae-11e9-8e70-7c5d91914f75.jpg)

**Comment by malbit** [comment]
> > Compiling stops with this error:
> > Project ERROR: Unknown module(s) in QT: svg
> > This is because in README someone forgot to add package "libqt5svg5-dev
> > " as dependancy. If it is not already in the system by chance, compilation fails.
> > Installation of this dependancy leads to a successful compiling.
> 
> I did compile without that lib successfully Ubuntu 18.04 desktop
> ![gui](https://user-images.githubusercontent.com/33489188/59881015-d34ad480-93ae-11e9-8e70-7c5d91914f75.jpg)

You could have that lib already installed.

But it is correct. I do admit I forgot about updating readme. It will be updated at next release which should be in the next couple of weeks :)

That missing libs which has go be installed is: libqt5svg5-dev

**Comment by UnicodeMan** [comment]
My OS is KDE Neon, for the record. Before installing that specific library, the wallet failed to compile. And hey -- it took me a mere minute to open an issue, and it's nothing compared to me duck'ing (duckduckgo instead of google) online for the resolve (two minutes). It will prevent other people from having to deal this in the future - and thats awesome.

**Comment by ArqTras** [comment]
You are right i got libs from other qt installation. 
In case You wanna some bounty dm wallet address to arqtras@arqma.com
Thanks for support

**Comment by UnicodeMan** [comment]
Heya - the last five letters of my wallet are "V5ix9". Again, thanks for the bounty. :)

**Comment by ArqTras** [comment]
> 
> 
> Heya - the last five letters of my wallet are "V5ix9". Again, thanks for the bounty. :)

tx id: 9b938795fa1cd9947d74cc4725dde31cc7e4c5e27f9e24a2d993da6137ac0712
Thank You
