### ISSUE TITLE
Git commit authorship

### ISSUE THREAD

**Issue by selsta** [arqma/arqma-gui#45]
Hello,

would it be possible to preserve Git commit authorship in the future? I see a lot of commits here that I did in https://github.com/monero-project/monero-gui with a different author.

Please look into the `--author` flag.

Thank you.

**Comment by malbit** [comment]
Sure we will do remember about it.
We will add informations about Monero-GUI codebase contributors at Readme if that will satisfy you.

**Comment by selsta** [comment]
Thank you.

> We will add informations about Monero-GUI codebase contributors at Readme if that will satisfy you.

This isn’t necessary, just retaining authorship information when merging / rebasing from upstream would be appreciated.
