### ISSUE TITLE
How to 'reload' the complete Blockchain on Windows?

### ISSUE THREAD

**Issue by bachph** [arqma/arqma-gui#50]
I shoud've got a transaction from mining of around 2 ARQ. Unfortunatly in the Wallet the transaction does not show up.

Can I somehow 'remove' the blockchain and let the daemon reload everything?

I read somewhere it is stored at C:\ProgrammData\arqma but there was only a log file.

I installed the wallet on another partition.

best regards,
Philipp

**Comment by ArqTras** [comment]
In settings / node / blockchain file location you can change place of data file for lmdb
Default is C:\ProgramData\arqma\lmdb
You can search for data.mdb and lock.mdb also p2pstate.bin if you choose non standard dir to place them
